::: safe_ds.exceptions.LearningError
