::: safe_ds.exceptions.PredictionError
